language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
# python 3.7 requires a newer linux distribution
matrix:
  include:
    - python: 3.7
      dist: xenial
script:
  - python setup.py test
